# Generated by Django 2.1 on 2018-08-05 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id of the competitions, according to API')),
                ('clear_name', models.CharField(max_length=255, verbose_name='Full name of the competition')),
            ],
        ),
        migrations.CreateModel(
            name='Federation',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Id of Federation, according to API')),
                ('clear_name', models.CharField(max_length=255, verbose_name='Full name of the federation')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id of the match according to API')),
                ('matchday', models.IntegerField(verbose_name='Matchday count for given league')),
                ('date', models.DateTimeField(verbose_name='Date of the match')),
                ('score_home_team', models.IntegerField(null=True, verbose_name='Score for the home team')),
                ('score_away_team', models.IntegerField(null=True, verbose_name='Score for the away team')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id of the Seasons, according to API')),
                ('clear_name', models.CharField(max_length=255, verbose_name='Full name of the given season')),
                ('start_date', models.DateTimeField(verbose_name='S tarting date of the season')),
                ('end_date', models.DateTimeField(verbose_name='End date of the season')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Competition', verbose_name='Competitions ID')),
                ('federation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Federation', verbose_name='Federation ID')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id of the Team, acording to API')),
                ('clear_name', models.CharField(max_length=255, verbose_name='Full name of the team')),
                ('short_name', models.CharField(max_length=50, verbose_name='Short name of the team')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='database.Team', verbose_name='Away team ID'),
        ),
        migrations.AddField(
            model_name='match',
            name='competitions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Competition', verbose_name='Competition ID'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='database.Team', verbose_name='Home Team ID'),
        ),
        migrations.AddField(
            model_name='match',
            name='seasons',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Season', verbose_name='Seasons ID'),
        ),
        migrations.AddField(
            model_name='competition',
            name='federation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Federation', verbose_name='Federation ID'),
        ),
    ]
