# Generated by Django 2.1 on 2018-08-05 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='competitions',
            new_name='competition',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='seasons',
            new_name='season',
        ),
    ]
