# Generated by Django 2.1 on 2018-08-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordUsers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id of the user according to discord')),
                ('name', models.CharField(max_length=2048, verbose_name='Name on of the user')),
                ('userLevel', models.IntegerField(default=0, verbose_name='UserLevel for the bot')),
            ],
        ),
    ]
