# Generated by Django 2.1 on 2018-08-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_discordusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchEventIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events', models.IntegerField(verbose_name='Event')),
                ('eventIcon', models.CharField(default='', max_length=50, verbose_name='Icon for the event')),
            ],
        ),
    ]
