# Generated by Django 2.1 on 2018-08-05 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_renamed_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='database.Team', verbose_name='Away team ID'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='database.Team', verbose_name='Home Team ID'),
        ),
        migrations.AlterField(
            model_name='match',
            name='matchday',
            field=models.IntegerField(null=True, verbose_name='Matchday count for given league'),
        ),
    ]
