# Generated by Django 2.1 on 2018-08-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_matcheventicon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Maximum length of command')),
                ('value', models.CharField(max_length=2048, verbose_name='Actual Command to be executed')),
            ],
        ),
    ]
