# Generated by Django 2.1 on 2018-08-06 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_added_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionWatcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_matchday', models.IntegerField(default=1, verbose_name='Current matchday of a given competition with season')),
            ],
        ),
        migrations.CreateModel(
            name='DiscordServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of the discord server')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='passed',
            field=models.BooleanField(default=False, verbose_name='Flag if the match is allready passed'),
        ),
        migrations.AddField(
            model_name='competitionwatcher',
            name='applicable_server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.DiscordServer', verbose_name='Id of the discord server'),
        ),
        migrations.AddField(
            model_name='competitionwatcher',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Competition', verbose_name='Id of the competition'),
        ),
        migrations.AddField(
            model_name='competitionwatcher',
            name='current_season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Season', verbose_name='Id of the current season'),
        ),
    ]
