# Generated by Django 2.1 on 2018-08-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matcheventicon',
            name='event',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Event'),
        ),
    ]
