# Generated by Django 2.1 on 2018-08-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_MetaDBs_and_field_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='association',
            field=models.CharField(default='', max_length=255, verbose_name='Country Code of competition'),
        ),
    ]
