# Generated by Django 2.1 on 2018-08-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20180817_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionwatcher',
            name='unified_channel',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Name of channel where its posted if not in a matchday channel'),
        ),
    ]
