# Generated by Django 2.1 on 2018-08-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_competition_association'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_status',
            field=models.IntegerField(null=True, verbose_name='Status of the match'),
        ),
    ]
