# Generated by Django 2.1 on 2018-08-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_competitionwatcher_unified_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionwatcher',
            name='role',
            field=models.IntegerField(default=None, null=True, verbose_name='Id for the role on the discord server'),
        ),
    ]
