# Generated by Django 2.1 on 2018-08-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_match_match_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='stage',
            field=models.IntegerField(default=0, verbose_name='Stage of the match, used for live match stuff'),
            preserve_default=False,
        ),
    ]
