# Generated by Django 2.1 on 2018-08-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_competitionwatcher_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionwatcher',
            name='category',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Category for the channel created by competitions'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Maximum length of command'),
        ),
    ]
