# Generated by Django 2.1 on 2018-08-29 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20180827_0818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=255, verbose_name='Name of the player that scored the goal')),
                ('minute', models.CharField(max_length=10, verbose_name='Minute this happened')),
                ('link', models.URLField(verbose_name='Link to the goal')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Match', verbose_name='Match that this goal belongs to')),
            ],
        ),
    ]
