# Generated by Django 2.1 on 2018-08-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255, verbose_name=' First name of the player')),
                ('lastName', models.CharField(max_length=255, verbose_name='Last name of the player')),
                ('birthDate', models.CharField(max_length=12, verbose_name='Birth date of the player')),
                ('imageLink', models.URLField(max_length=255, verbose_name='Link to the image of the player')),
            ],
        ),
    ]
